[project]
name = "ipo-extract"
version = "1.0.1"
description = "负责ipo招股说明书的表格抽取"
requires-python = ">=3.12"
dependencies = [
    "openpyxl",
    "requests",
    "urllib3",
    "pdfplumber",
    "OpenAI",
    "pandas",
]